# Generated by Django 3.1.2 on 2020-10-23 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201019_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 0, 4, 20, 181101)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 0, 4, 20, 181101)),
        ),
    ]
